### PR TITLE
Activate Timer in Boil and Mash Steps

### PR DESCRIPTION
**Pull request by BrauereiAlt**
Forcing self.timer.is_running to True may be a bit of a kludge, but it works for now.

### CODE REVIEW

**Comment by avollkopf** [comment]
In the if clause you could replace 

`self.timer == None:` 

with 

`self.timer._task == None:`

and you are done.

See also her: https://github.com/avollkopf/cbpi4-BM_Steps/blob/main/cbpi4-BM_Steps/__init__.py

**Comment by BrauereiAlt** [comment]
Thanks, I need to better acquaint myself with asyncio.  Do we still need to be concerned that timer.is_running is not True after timer.start()?

And thanks for sharing your customized BrauMeister steps.  I see you already resolved assigning the target temp to the kettle controller.  Would be nice to see that in the main build.

**Comment by avollkopf** [comment]
@BrauereiAlt I had one issue on this topic open in the past but somehow lost track since I managed it via the self.timer._task. This is working quite stable. I already tested an 'empty' mash with water and the program went through all of my steps incl. the automatic activation and deactivation of the Kettle Logic. Hence, I am not worried about the timer.is_running. 

OffTopic:
I have a couple of more plugins and will upload an updated version of the PID Autotune tonight incl. the new Notifications. (Just in case you want to browse them and use some of the code)

**Comment by BrauereiAlt** [comment]
Vielen Dank!

**Pull request merged**
